import { ConnectButton } from '@rainbow-me/rainbowkit';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Navbar from "../components/Navbar";
import Link from "next/link";
declare global {
  interface Window {
    tronWeb: any;
  }
}
import { useState, useEffect } from 'react';

const Home = () => {
  const [tronWebState, setTronWebState] = useState({
    installed: false,
    loggedIn: false,
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      if (window.tronWeb) {
        setTronWebState({
          installed: true,
          loggedIn: window.tronWeb.ready,
        });
      } else {
        window.addEventListener('message', ({ data }) => {
          if (data.message && data.message.action == 'setAccount') {
            setTronWebState({
              installed: true,
              loggedIn: window.tronWeb && window.tronWeb.ready,
            });
          }
        });
      }
    }
  }, []);

  const ConnectWalletButton = () => {
    if (!tronWebState.installed) {
      return <div>TronLink is not installed. Please install it.</div>;
    } else if (!tronWebState.loggedIn) {
      return <div>Please log in to TronLink.</div>;
    } else {
      return <div>TronLink is installed and logged in.</div>;
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>JustBet</title>
        <meta
            content="Generated by TronLink"
            name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Navbar/>

      <main className={styles.main}>

          <h1 className={styles.title}>Welcome to JustBet</h1>

          <p className={styles.description}>
              A decentralized casino powered by{' '}
              <a href="https://tronlink.org/" className={styles.link}>
                  TronLink
              </a>
          </p>

        <div className={styles.grid} style={{display: 'flex', justifyContent: 'center'}}>
            <Link href="/DiceRoll">
                <a className={styles.card}>
                    <h2>Dice Roll &rarr;</h2>
                    <p>Roll a 100 sided Die to win some TRX</p>
                </a>
            </Link>
        </div>
          <ConnectWalletButton />
      </main>

      <footer className={styles.footer}>
        <a href="https://tronlink.org/" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at TronLink
        </a>
      </footer>
    </div>
  );
};

export default Home;


