import { ConnectButton } from '@rainbow-me/rainbowkit';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Navbar from "../components/Navbar";
import Link from "next/link";

const Home = () => {
  return (
      <div className={styles.container}>
        <Head>
          <title>RainbowKit App</title>
          <meta
              content="Generated by @rainbow-me/create-rainbowkit"
              name="description"
          />
          <link href="/favicon.ico" rel="icon" />
        </Head>

        <Navbar/>

        <main className={styles.main}>

            <h1 className={styles.title}>Welcome to LedgerLuck</h1>

            <p className={styles.description}>
                A decentralized casino powered by{' '}
                <a href="https://rainbow.me" className={styles.link}>
                    RainbowKit
                </a>
            </p>

          <div className={styles.grid}>
            <Link href="/CoinFlip">
              <a className={styles.card}>
                <h2>Coin Flip &rarr;</h2>
                <p>Flip a coin and win some ETH.</p>
              </a>
            </Link>
          </div>
            <ConnectButton />
        </main>

        <footer className={styles.footer}>
          <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
            Made with ❤️ by your frens at 🌈
          </a>
        </footer>
      </div>
  );
};

export default Home;
